### ISSUE TITLE
Add USP

### ISSUE THREAD

**Issue by scriptzteam** [carey-li/isnzbup#1]
usenet.cat

**Comment by cry** [comment]
Doesn't appear to be up

> Lunar :: ~ » telnet usenet.cat 119
> Trying 104.27.139.130...
> telnet: connect to address 104.27.139.130: Connection refused

vs 

> Lunar :: ~ » telnet news.newsgroup.ninja 119
> Trying 69.16.179.23...
> Connected to news.iad.highwinds-media.com.
> Escape character is '^]'.
> 200 Welcome (fx20.iad)

**Comment by scriptzteam** [comment]
news.usenet.cat ;)

**Comment by cry** [comment]
Will update in next push

**Comment by cry** [comment]
```
Lunar :: ~ » telnet news.usenet.cat 563
Trying 188.165.29.16...
telnet: connect to address 188.165.29.16: Connection refused
telnet: Unable to connect to remote host

Lunar :: ~ » telnet news.usenet.cat 119                                                                                        
Trying 188.165.29.16...
telnet: connect to address 188.165.29.16: Connection refused
telnet: Unable to connect to remote host
```

Doesn't seem to work?

**Comment by cry** [comment]
Added 563, had a networking issue preventing me from connecting.
